on:
  - push
jobs:
  compile-sketch:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: arduino/compile-sketches@v1
      with:
        sketch-paths: |
          - ./
        libraries: |
          - LiquidCrystal.h
          - LiquidCrystal.h
          - Stepper.h
          - Arduino.h
          - Wire.h

